services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: simple_chat_backend
    restart: always
    env_file:
      - .env
    volumes:
      - sqlite-db:/root/db:rw
      - logs:/logs:rw
    expose:
      - "8000"
    networks:
      main:

  web-server:
    build:
      context: .
      dockerfile: ./web_server/Dockerfile
    container_name: simple_chat_nginx
    restart: always
    volumes:
      - /etc/letsencrypt/live/fredcv.ru:/etc/nginx/ssl/:ro
    ports:
      - "127.0.0.1:8802:443"
    networks:
      main:
    depends_on:
      - backend


networks:
  main:
    driver: bridge


volumes:
  sqlite-db:
  logs:
